#ifndef CONFIG_H
#define CONFIG_H

#define APP_NAME "FEX"
#define APP_VERSION "0.1.0"
#define APP_AUTHOR "DavidsonRafaelK"

#define WINDOW_DEFAULT_WIDTH 800
#define WINDOW_DEFAULT_HEIGHT 600
#define WINDOW_TITLE "FEX"
#define WINDOW_RESIZABLE true

#define WINDOW_POSITION_X 100
#define WINDOW_POSITION_Y 100

#define WINDOW_MIN_WIDTH 400
#define WINDOW_MIN_HEIGHT 300

#define FPS_TARGET 60
#define FRAME_TIME (1000 / FPS_TARGET)

#define ENABLE_LOGGING true
#define LOG_LEVEL_DEFAULT LOG_LEVEL_DEBUG

#endif
